### ISSUE TITLE
When moving troops after the battle, the player should not be able to move less troops than they used to attack

### ISSUE THREAD

**Issue by MohamedZalat** [xilingdc/3110ProjectRisk#24]

**Comment by xilingdc** [comment]
hey, i am trying to fix this, but I don't understand what do you mean about "they used to attack", for example, if I have 7 troops, and the other has 2 troops, I defeated them, so the minimum troop number that I can move to the new occupied country is 2?

**Comment by MohamedZalat** [comment]
No, when you attack you are asked to select how many die rolls you are using. If you use 2 for example, you can at the very least move 2 troops to the new country if you claimed it.

________________________________

**Comment by xilingdc** [comment]
I see, thank you.
