### ISSUE TITLE
When attacking a country you should either select the attacking country first or the country you want to attack. It should then give you the list of available countries to attack/use to attack.

### ISSUE THREAD

**Issue by MohamedZalat** [xilingdc/3110ProjectRisk#3]

**Comment by xilingdc** [comment]
but this is not in the descriptions,  I asked prof, he only mentioned is Wikipedia's rule

**Comment by MohamedZalat** [comment]
You need to have a proper interface for the game when it is text based. I should not need to look at an image of the board while using your command line interface. When you play a text based game, the game HAS to provide you with valid options for you to select from.
________________________________
