### ISSUE TITLE
UML class diagram: Many issues with your diagram

### ISSUE THREAD

**Issue by MohamedZalat** [xilingdc/3110ProjectRisk#9]
1) Command is not composed of CommandWord. commandWord parameter of Command is a string not a CommandWord instance.
2) Country should have a has-a relationship with itself. Note: has-a relationship is an empty diamond, not a solid one.
3) Player should have a has-a relationship with country, not a dependency arrow.
4) Model should have a has-a relationship with player, not a dependency arrow.
5) Model should have a has-a relationship with Parser, not a dependency arrow.
-----
There are more issues, but you should be able to figure them out yourself from the ones I gave you.

**Comment by MohamedZalat** [comment]
You still did not address the issues I mentioned here in M2

**Comment by xilingdc** [comment]
could you please point out which part I did wrong, 1 is no longer exist, 2,3,4, I already change dependency relationships to association relationships, and 5 is no longer exist

**Comment by MohamedZalat** [comment]
association (dependency arrow) =/= aggregation (has-a)
aggregation :- class has the other class as a member (i.e. a private/public member) - has a diamond
association :- class uses the other class but does not have it as a member - is just an arrow

You need to know the difference between the two relationships. Read the UML guide or check through the lecture material.

**Comment by xilingdc** [comment]
ok, so should model also has-a relationship with controller? and view has-a relationship with model?
